### ISSUE TITLE
pipe2xeasy/ucsf fail 

### ISSUE THREAD

**Issue by mayzel** [yokochi47/xyza2pipe#2]
Hi,

I have a  problem converting 3D pipe spectrum to xeasy/ucsf, while conversion to AZARA seems to work fine.
Please find HNCO spectrum at https://www.dropbox.com/s/p49pob6csdlm55z/HNCO.ft3?dl=0 

Thanks,
Maxim

--------------------------------------------
 pipe2azara --out HNCO.spc < HNCO.ft3
Receiving 128 of 128 ( -> pipe2azara) ...           
--------------------------------------------
pipe2ucsf --out HNCO.ucsf < HNCO.ft3

Receiving 128 of 128 ( -> pipe2ucsf) ...                                                                                                                                        
Reading HNCO.ucsf ...
Axis Label |        H         C         N
Data Size  |      487       336       128
Block Size |       30        21         8
Obs. Freq. |  799.870   201.127    81.050 [MHz]
Spec.Width |  3048.63   2414.29   2918.86 [Hz]
Orig.Freq. |  3765.65  33393.88   8127.28 [Hz]
Spec.Center|     4.70    172.00    118.00 [ppm]

Spectra file HNCO.ucsf: Partially broken. (Actual=87721428 Expected=83780148)
Try to fix data points from file size...
--------------------------------------------
pipe2xeasy --out HNCO.3D.16 < HNCO.ft3

Receiving 128 of 128 ( -> pipe2xeasy) ...                                                                                                                                       
Reading HNCO.3D.16 ...
Axis Label |        H         C         N
Data Size  |      487       336       128
Block Size |       30        21         8
Dim. Order |        1         2         3
Obs. Freq. |  799.870   201.127    81.050 [MHz]
Spec.Center|     4.70    172.00    118.00 [ppm]
Spec.Width |  3048.63   2414.29   2918.86 [Hz]
Orig.Freq. |  3765.65  33393.88   8127.28 [Hz]

Spectra file HNCO.3D.16: Partially broken. (Actual=41297714 Expected=41889792)

**Comment by yokochi47** [comment]
Dear Maxim,

Thank you for your bug report and providing us test spectra.

In the spectra, I found a problem that data point of H axis was unexpectedly odd number and that invalid block size occurred. The new release, v1.0.3, can manage the issue, but you had better to avoid odd number of data point to gain real performance of spectral viewer applications, such as Sparky, NMRView, Azara, XEASY.

Anyway, please test the new release.

Best regards,

Masashi

**Comment by mayzel** [comment]
Dear Masashi,

Thank you for a quick reply and bug fix, it works at least with XEASY now.
I don’t think odd number of points matters for the direct dimension. 
As an input for NMRPipe spectrum of course  has even number of points, but after the region of interest extraction it may become odd and I have not noticed any slowdown in CCPN Analysis because of this.

Best regards,
Maxim

**Comment by yokochi47** [comment]
The issue has been resolved by release 1.0.3.

Thank you,
