### ISSUE TITLE
problem with NMRView formatted files from NMRFx

### ISSUE THREAD

**Issue by kojetinlab** [yokochi47/xyza2pipe#3]
I have some NMR data processed with NMRFx (https://nmrfx.org/nmrfx/analyst) that are saved in NMRView format, but the files are not recognized properly by nv2pipe:

```
% ~/xyza2pipe/nv2pipe --in hsqc.nv                     
Reading hsqc.nv ...
Axis Label |        H         N
Block Size |       64        64
Data Size  |     1169       726
Obs. Freq. |  700.133    70.952 [MHz]
Spec.Width |  4777.91   2515.91 [Hz]
Orig.Freq. |  4419.49   7290.21 [Hz]
Spec.Center|     9.72    120.43 [ppm]

Spectra file hsqc.nv: Partially broken. (Actual=3737600 Expected=3396824)
Try to fix data points from file size...
Failed.
```

Could the file format of the nv file saved from NMRpipe process vs. NMRFx differ?

**Comment by yokochi47** [comment]
Spectral editing (truncation) may effect, NMRFx changes header for their need to express the truncation, but real data may be preserved as is that causes inconsistency between the header information and file size.
If you can send the file, I may find a solution.

Best,

**Comment by kojetinlab** [comment]
Thanks. What is the best way to send a file to you (~4 MB)?

**Comment by yokochi47** [comment]
OK.
Please send me a mail. The address is shown in my profile,  @yokochi47 .

**Comment by yokochi47** [comment]
Thank you for providing the file.

At first, the data point (1169) is not multiplier of block size (64) for the 1st dimension. It was error as NMRView format. Then, I found zero filling in spectral data region of the file. I think that spectral truncation occurred inside of NMRFx but it is not properly reflected into the NMRView format. xyza2pipe tied to estimate the real data point from block size and file size, but it failed.

There is several options:
1) I have updated xyza2pipe package, v1.0.5, not to try to estimate the data size in case of these inconsistency.
Please run ~/xyza2pipe/nv2pipe --in hsqc.nv --no-rescue and want to see what happens next.

If the data point (1169) for the 1st dimension is correct, the zero-filled spectral region wiped off flawlessly. Otherwise, spectra is corrupt.

2) Please check whether the generated file, hsqc.nv, is successfully recognized by NMRView. If it is not, it is NMRFx's fault.

Best regards,

**Comment by kojetinlab** [comment]
Thanks for the information.

Here is the output without --no-rescue:

% nv2pipe --in hsqc.nv > test.ft2
Reading hsqc.nv ...
Axis Label |        H         N
Block Size |       64        64
Data Size  |     1169       726
Obs. Freq. |  700.133    70.952 [MHz]
Spec.Width |  4777.91   2515.91 [Hz]
Orig.Freq. |  4419.49   7290.21 [Hz]
Spec.Center|     9.72    120.43 [ppm]

Spectra file hsqc.nv: Partially broken. (Actual=3737600 Expected=3396824)
Try to fix data points from file size...
Failed.

Here is the output with--no-rescue:

% nv2pipe --in hsqc.nv --no-rescue > test.ft2
Reading hsqc.nv ...
Axis Label |        H         N
Block Size |       64        64
Data Size  |     1169       726
Obs. Freq. |  700.133    70.952 [MHz]
Spec.Width |  4777.91   2515.91 [Hz]
Orig.Freq. |  4419.49   7290.21 [Hz]
Spec.Center|     9.72    120.43 [ppm]

Spectra file hsqc.nv: Partially broken. (Actual=3737600 Expected=3396824)

The second command (with --no-rescue) writes a file (hsqc.nv), but the file size is very small (4 KB) and NMRDraw gives and error when trying to read it:

DATAIO File Read Error 0.
Request: 3394776 Actual: 0.
SYSREAD Message: Success
Error reading file, mv_read

Best,
Doug

**Comment by yokochi47** [comment]
> % nv2pipe --in hsqc.nv --no-rescue > test.ft2

Please run the following command and read test of both hsqc.nv and new_hsqc.nv:
nv2pipe --in hsqc.nv --no-rescue | pipe2nv --out new_hsqc.nv

Thank you,

**Comment by kojetinlab** [comment]
That command generated a new_hsqc.nv file of a slightly larger size (4.1 MB) compared to the original hsqc.nv file (3.6 MB). However, after reading the new_hsqc.nv file into NMRViewJ no data are displayed. When I click a button to automatically determine the appropriate contour level to display (I think based on the noise level of the data) I get an error indicating it "cannot find level for data"

Output:

```
% nv2pipe --in hsqc.nv --no-rescue | pipe2nv --out new_hsqc.nv
Reading hsqc.nv ...
Axis Label |        H         N
Block Size |       64        64
Data Size  |     1169       726
Obs. Freq. |  700.133    70.952 [MHz]
Spec.Width |  4777.91   2515.91 [Hz]
Orig.Freq. |  4419.49   7290.21 [Hz]
Spec.Center|     9.72    120.43 [ppm]

Spectra file hsqc.nv: Partially broken. (Actual=3737600 Expected=3396824)

Receiving 1 of 1 ( -> pipe2nv) ...                                                                                     

Reading new_hsqc.nv ...
Axis Label |        H         N
Block Size |      167       121
Data Size  |     1169       726
Obs. Freq. |  700.133    70.952 [MHz]
Spec.Width |  4777.91   2515.91 [Hz]
Orig.Freq. |  4419.49   7290.21 [Hz]
Spec.Center|     9.72    120.43 [ppm]
```

**Comment by yokochi47** [comment]
New replaced release v1.0.5 can fix data point for the case.
I confirmed that new_hsqc.nv could be loaded and displayed in NMRView.
'--no-rescue' option is not required and removed from the program.
Please test it again.

Best,

**Comment by kojetinlab** [comment]
I tested and confirm this update works for me. Thank you!

**Comment by yokochi47** [comment]
Yor're welcome. Done with v1.0.5 release.
