### ISSUE TITLE
Inconsistent XEASY parameter file name

### ISSUE THREAD

**Issue by hfswetton** [yokochi47/xyza2pipe#4]
Hi,

I just came across a small inconsistency in the way that XEASY parameter filenames are generated which causes a slightly confusing error message in certain cases.

In `pullxeasy.c` there is a fallback for if the spectrum file does not use the usual extension `".16"`, for example in `pullxeasy2d()` (line 39):

```
if (strstr(spectra2d, ".16"))
  strreplacecpy(parfile, spectra2d, ".16", ".param");
else
  sprintf(parfile, "%s.param", spectra2d);
```

whereas in `checkxeasy()` (line 52) from `checkxeasy.c` this is not used:

```
strreplacecpy(parfile, filename, ".16", ".param");
```

This means that using `pipe2xeasy` with an output file not containing `".16"` tries to read the output spectrum file as a parameter file (as the `strreplacecpy()` call does not change the filename string) and results in the following error message:

> Parameter file [...]: Not XEASY parameter file.
> Couldn't find description such as 'Version'.

Would it be possible (/sensible) to implement the same fallback in `checkxeasy()` or to present a warning if the output file is missing the `".16"` extension?

Best regards,
Henry

**Comment by yokochi47** [comment]
Hi,

You're correct. There is a case that the tool can not handle XEASY parameter filename generated by the tool itself. New version, v1.0.6, will be released to address this issue.

Thank you for your notice.

Masashi

**Comment by hfswetton** [comment]
Many thanks for the quick response and fix!

Best, Henry
